#!/bin/sh
TOKEN=$1
ORG=$2
curl -u $TOKEN:x-oauth-basic -s https://api.github.com/orgs/$ORG/repos?per_page=200 | ruby -rubygems -e 'require "json"; JSON.load(STDIN.read).each { |repo| %x[git clone #{repo["ssh_url"]} ]}'
